name: Patch and Push Docker Image

on:
  schedule:
    # Every 1st day of month 03:00 JST → 18:00 UTC
    - cron: "0 18 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  patch-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      # Checkout repository
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Login to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Get today's date in YYYY-MM-DD format
      - name: Generate date tag
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # Execute patch-image.sh to replace local files
      - name: Patch the Docker image
        run: |
          bash patch-image.sh \
            codiumai/pr-agent:0.29-github_action \
            /app/pr_agent/settings/pr_reviewer_prompts.toml \
            pr_reviewer_prompts.toml \
            security-pr-agent:latest

      # Tag for GHCR
      - name: Tag image for GHCR
        run: |
          docker tag \
            security-pr-agent:latest \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}
          docker tag \
            security-pr-agent:latest \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # Push image
      - name: Push image to GHCR
        id: push
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.date.outputs.date }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # Output the digest of the latest image
          echo "digest=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest | cut -d'@' -f2)" >> $GITHUB_OUTPUT

      - name: Generate SBOM
        uses: anchore/sbom-action@f325610c9f50a54015d37c8d16cb3b0e2c8f4de0 # v0.18.0
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          format: "cyclonedx-json"
          output-file: "sbom.cyclonedx.json"

      - name: Attest
        uses: actions/attest-sbom@115c3be05ff3974bcbd596578934b3f9ce39bf68 # v2.2.0
        id: attest
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          sbom-path: "sbom.cyclonedx.json"
          push-to-registry: true
